{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "forge-operator.resourceName" (dict "suffix" "serving-cert" "context" $) }}
    {{- end }}
  name: {{ include "forge-operator.resourceName" (dict "suffix" "mutating-webhook-configuration" "context" $) }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "forge-operator.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-forge-ningendo7-github-io-v1alpha1-application
  failurePolicy: Fail
  name: mapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - forge.ningendo7.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
{{- end }}
