---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - forge.ningendo7.github.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - forge.ningendo7.github.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - forge.ningendo7.github.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
