{{- if and .Values.metrics.enabled .Values.metrics.secure .Values.metrics.reader.serviceAccountBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "forge-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "forge-operator.resourceName" (dict "suffix" "metrics-reader-rolebinding" "context" $) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "forge-operator.resourceName" (dict "suffix" "metrics-reader" "context" $) }}
subjects:
{{- range .Values.metrics.reader.serviceAccountBindings }}
- kind: ServiceAccount
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}
{{- end }}
